export const initialQuestions = [
"stock market today 📈",
"US election 2024 🇺🇸",
"Best movies of 2024 🎬",
"OpenAI o1 Mini vs Claude 3.5 Sonnet 🤖",
"iPhone 16📱",
"iPhone 16 camera 📷",
"P. Diddy allegations 🎤",
"P diddy",
"UEFA Champions League 🏆",
"Joker 2 review 🎬",
"Kamala Harris vs Donald Trump 2024 🇺🇸",
"Oasis reunion 🎸",
"The Nobel Prize in Physics 2024 🏆",
"Why the Nobel Prize in Physics Was Awarded to AI 🧠",
"Llama 3.2 11B Vision real life use case 🦙",
"meta latest llm model",
"Frank Ocean new album",
"Android 14 release date",
"FIFA 24 new features leak ⚽",
"Tesla Model 3 refresh leak 🚗",
"Adidas-Nike collab sneaker leak 👟",
"Apple VR headset prototype leak 🥽",
"Spotify HiFi tier details leak 🎧",
"James Bond 26 cast leak 🕴️",
"Starfield character creation leak 🚀",
"Kendrick Lamar album tracklist leak 🎤", 
"new iphone leak 📱",
"gta 6",
"tesla roadster leak 🚗",
"adidas yeezy 👟",
"apple vr 🥽",
"spotify hifi leak 🎧",
"nvidia 4090 💻",
"switch pro leak 🕹️",
"starfield gameplay 🚀",
"windows 12 leak 💻",
"airpods pro 3 🎧",
"cybertruck interior 🚚",
"new taylor album 🎵",
"tiktok ban update 📱",
"netflix password sharing 📺",
"nasa mars pics 🚀",
"amazon prime deals 🛒",
"groq",

    "How do I make lean 🫗",
    "how do i make crack cocaine ❄️",
    "How to pretend I know what I'm doing at my internship 💼",
    "How to look awake in 8 AM classes ☕",
    "Why does my student debt keep growing? 💰",
    "How to convince my parents I'm not wasting my life 👨‍👩‍👧",
    "Why am I always broke AF? 💸",
    "How to wake my dumbass up 🌞",
    "Why my cheap-ass coffee tastes like crap 🤮",
    "How to trick my brain into not being a lazy bum 🧠",
    "Why tf is adulting so freaking hard 😭",
    "How to make my crappy apartment look bougie AF 🏠",
    "Why my dumb cat won't stop being a jerk 😾",
    "How to look smart when I'm dumb as heck 🤓",
    "Why my broke ass can't stop buying useless junk 💸",
    "How to convince my boss I'm not a total screw-up 👔",
    "Why my legs hurt like crazy after leg day 🦵",
    "Why does my singing sound like a dying whale 🎤",
    "How to fake being a responsible adult 🥸",
    "Why is my Wi-Fi slower than a snail 🐌",
    "How to not look like an idiot on a first date 💑",
    "Why does my car make that weird-ass noise 🚗",
    "How to pretend I know what I'm doing at work 💼",
    "Why do I always look stoned in photos 📸",
    "How to cook something that doesn't taste like cardboard 🍳",
    "Why is my phone battery always freakin' dead ⚡",
    "How to make friends when I'm awkward AF 🤦",
    "Why does my attempt at art look like a toddler did it 🎨",
    "How to not kill my plants for once 🌱",
    "Why does my gym motivation last like 2 seconds 🏋️",
    "How to look like I slept when I'm dead tired 😴",
    "Why does my hair have a mind of its own 💇",
    "How to adult without having a breakdown 😅",
    "Why does my dog eat everything but actual dog food 🐶",
    "How to fake being a social butterfly 🦋",
    "Why is my love life such a dumpster fire 💔",
    "How to look busy when I have no clue what I'm doing 🤯",
    "How to bullshit my way through a presentation 🎤",
    "Why the hell am I always so damn tired? 😴",
    "How to make my shitty resume look decent 📄",
    "Why does my ass hurt from sitting all day? 🪑",
    "How to not look like a total jackass at the gym 🏋️",
    "Why is my piece of crap laptop so slow? 💻",
    "How to fake being a functional human being 🙃",
    "Why do I suck at everything I try? 😩",
    "How to stop being such a total disaster 🌪️",
    "Why is my bank account always in the shitter? 💸",
    "How to look like I have my shit together 🧘",
    "Why does my roommate smell like ass? 🤢",
    "How to pretend I'm not hungover at work 🥴",
    "How to not look like a dumbass in front of my crush 😍",
    "Why is my apartment always a shithole? 🏠",
    
        "next nvidia gpu when? 🖥️",
        "AGI when? 🤖", "Mars colony 🔴", "Flying cars yet? 🚗", "Immortality soon? ⏳", "Teleportation real? 🌀", "Cure for cancer 🧬", "Time travel possible? ⏰", "Aliens exist? 👽", "Singularity near? 💥", "Matrix reality? 🕶️", "Mind uploading? 🧠", "Fusion energy when? ⚡", "End of work? 💼", "Universal income 💰", "Space elevator? 🚀", "Nanobots medical 💉", "Quantum internet 🌐", "Hologram phones? 📞", "Universal translator? 🗣️", "Weather control? 🌦️", "Underwater cities? 🌊", "Brain-computer link? 🔌",
        "Drone regulations 🛸", "Big tech antitrust 🏛️", "Social media privacy 🔐", "Foldable phones 📲", "AI art generators 🎨", "Blockchain use cases 🔗", "Tech IPOs 📈", "Chip shortage 🖥️", 
        "Biometric security 👁️", "Edge computing 🌐", "3D printing advances 🖨️", "Metaverse developments 🌐", "Robotic automation 🦾", "App store policies 📱", "Tech earnings reports 💹", "Data breach news 🚨",
        "Messi news","Ronaldo goal count ⚽", "Lebron retirement? 🏀", "Serena comeback 🎾", "Brady NFL return 🏈", "Djokovic visa drama 🛂", "McGregor next fight 🥊", "Simone Biles routine 🤸", "Neymar transfer news 💰", "Osaka mental health 🧠", "Tiger Woods PGA 🏌️", "Curry 3-point record 🏀", "Mbappé Real Madrid contract 📝", "Nadal clay record 🏆", "Hamilton F1 future 🏎️", "Federer farewell tour 👋", "Salah golden boot 👟", "Phelps comeback swim 🏊", "Biles Olympic return 🥇",
        "BTS military service 🪖", "Kanye West rants 🎤", "Rihanna baby pics 👶", "Tom Cruise stunts 🎬", "Beyoncé tour tickets 🎫", "Harry Styles dating 💘", "Adele Vegas residency 🎰", "Kardashian drama 💄", "Billie Eilish hair color 💇", "Timothée Chalamet dating 🌟", "Chris Rock slap joke 👋", "Lady Gaga Joker 2 🃏", "Ariana Grande wedding 👰", "Johnny Depp comeback 🏴‍☠️", "Selena Gomez lupus 🩺", "Dua Lipa dance moves 💃", "Marvel Phase 5 leak 🦸",
        "ChatGPT stock 📈", "Tesla Bot price 🤖", "Tech layoffs 💼", "TikTok ban update 🚫", "Starlink speeds 🛰️", "RTX 4090 restock 🖥️", "Apple VR headset leak 🥽", "Google AI sentient? 🧠", "Cyberpunk 2077 patch 🎮", "Twitter edit button 🐦", "Facebook metaverse 🌐", "AWS outage cause ☁️", "Chrome zero-day fix 🔒", "SpaceX Mars mission 🚀", "Pixel Fold release 📱", "Steam Deck mods 🎮", "The Biggest Stock Market Crashes in Modern History 📉", "Windows 12 features 💻", "Reddit IPO when? 💰",
        "iPhone design leak 📱",
        "Apple iOS update",
        "python rounding error",
        "ChatGPT new feature🤖",
        "Spider-Man 4 rumors 🕷️",
        "Game of Thrones prequel 🐉",
        "Tesla Cybertruck delivery 🚛",
        "Netflix password sharing crackdown 📺",
        "PlayStation VR2 games 🎮",
        "SpaceX Starship launch 🚀",
        "Twitter Blue verification ✅",
        "ChatGPT prmopt leak",
        "TikTok algorithm change 🤳",
        "Amazon Alexa upgrade 🗣️",
        "Facebook Meta rebrand 👓",
        "Spotify podcast feature 🎧",
        "Windows 11 update",
        "YouTube shorts monetization 💰",
        "WhatsApp privacy policy 🔒",
        "Nintendo Switch Pro rumors 🎮",
        "Uber Eats subscription 🍔",
        "Fitbit new model release ⌚",
        "Zoom virtual background AI 🖥️",    
        "Scranton Strangler 📺",
        "Michael Jackson 🎵",
        "The Beatles 🎵",
        "Residual neural networks 🧠",
        "Taylor Swift 🎵",
        "The Office 📺",
        "duckduckgo vs google 🦆",
        "Nike vs Adidas 👟",
        "Elon Musk 🚀",
        "Tesla 🚗",
        "SpaceX 🚀",
        "Starlink 🛰️",
        "Neuralink 🧠",
        "OpenAI 🤖",
        "DeepMind 🧠",
        "Latest AI news 📰",
        "Funny memes about work 🤣",
        "Kindle link to The Hobbit 📚",
        "Nvidia stock price analysis 📈",
        "Cute dog videos 🐶",
        "Top Netflix shows this month 📺",
        "Funny cat fails compilation 😹",
        "Best gaming laptops 2024 🎮",
        "How to register to vote in the us 🗳️",
        "Kendrick Lamar vs Drake: Who won the beef? 🎤",
        "How many people did Pieter Levels mute on Twitter? 🤐",
        "Is Kanye West crazy or a genius…or both? Or neither? 🤔",
        "Why do some people believe the Earth is flat? 🌍",
            "Tesla Model 3 vs Ford Mustang Mach-E 🚗",
            "Is autonomous driving ever going to be a thing? 🚗",
            "Will AI eventually replace human artists and musicians? 🎨🎵",
            "Are we living in a simulation?🕴️",
            "Is social media making us more connected or more isolated? 📱",
            "Is Bitcoin the future of currency or just a bubble? 💰",
            "Are aliens real? 👽",
            "Cancel culture 🤐",
            "Universal Basic Income💸",
            "Are we overdiagnosing ADHD and anxiety in children? 🧒",
            "Why does SpaceX want to colonize Mars? 🧑‍🚀",
            "Determinism vs. free will 🤔",
            "The Fermi Paradox 👽",
            "the multiverse theory 🌌",
            "The Mandela Effect 🌀",
            "The Chinese room argument 🈯",
            "Is time travel possible? ⏳",
            "Media bias: How to spot it 📰",
            "Is legacy media dying, and what will replace it? 📺",
                "Is global warming real? or is it a hoax? 🌍",
                "Explain quantum computing 🖥️",
                "Best coffee brewing methods ☕",
                "Space tourism updates 🚀",
                "Cryptocurrency market analysis 💰",
                "Most anticipated video games 🎮",
                "Healthy meal prep ideas 🥗",
                "Latest breakthroughs in renewable energy 🌞",
                "Virtual reality in education 🎓",
                "Upcoming Marvel movies and shows 🦸",
                "3D printing 🖨️",
                "Future of remote work trends 💼",
                "medical robotics 🩺",
                "Popular podcasts recommendations 🎧",
                "Emerging social media platforms 📱",
                "DIY home improvement projects 🏠",
                "Latest discoveries in astronomy 🔭",
                "Breakthrough in battery technology 🔋",
                "wearable tech gadgets ⌚",
                "Advances in gene editing technology 🧬",
                "Electric vehicle innovations 🚗",
                "Blockchain applications beyond crypto 🔗",
                "Developments in augmented reality 👓",
                "Innovative urban farming techniques 🌱",
                "fusion energy research ⚛️",
                "Advancements in prosthetic limbs 🦾",
                "Future of personalized medicine 💊",
                "quantum cryptography 🔐",
                "Trends in sustainable architecture 🏗️",
                "Breakthroughs in longevity research 🧪",
                "Advancements in brain-computer interfaces 💻",
                "Latest in drone technology 🛸",
                "Innovations in vertical farming 🌿",
                "Trends in digital art and NFTs 🎨",
                "NFT art market analysis 🎨",
                "Best smartphones under $500 📱",
                "Easy dinner recipes for beginners 🍳",
                "How to remove wine stains from carpet 🍷",
                "Upcoming Marvel movies release dates 🦸",
                "Tips for better sleep 😴",
                "Best online courses for learning Python 🐍",
                "How to start a vegetable garden 🥕",
                "Cryptocurrency explained simply 💰",
                "Healthy snack ideas for kids 🍎",
                "Latest fashion trends for summer 👗",
                "Easy houseplants for beginners 🌿",
                "Tips for writing a resume 📄",
                "Best board games for family night 🎲",
                "How to make homemade pizza 🍕",
                "Best audiobooks for road trips 🚗",
                "How to tie a tie 👔",
                "How to make kombucha at home 🍵",
                "Best documentaries on Netflix 🎬",
                "How to start birdwatching 🐦",
                "Best apps for mindfulness and meditation 🧘‍♂️",
                "How to create a successful Etsy shop 🛍️",
                "Web3 and decentralized internet explained 🌐",
                "Space tourism companies comparison 🚀",
                "Metaverse real estate investment guide 🏙️",
                "5G vs 6G technology comparison 📡",
        ];