export const initialQuestions = [
"Latest AI news 📰",
"Funny memes about work 🤣",
"OpenAI o1 Mini vs Claude 3.5 Sonnet 🤖",
"iPhone 16📱",
"Kindle link to The Hobbit 📚",
"Nvidia stock price analysis 📈",
    "Is Kanye West crazy or a genius…or both? Or neither? 🤔",
    "Tesla Model 3 vs Ford Mustang Mach-E 🚗",
    "Is autonomous driving ever going to be a thing? 🚗",
    "Is Kanye West crazy or a genius…or both? Or neither? 🤔",
    "Tesla Model 3 vs Ford Mustang Mach-E 🚗",
    "Is autonomous driving ever going to be a thing? 🚗",
    "Will AI eventually replace human artists and musicians? 🎨🎵",
    "Are we living in a simulation? Matrix theory explained 🕴️",
    "Is social media making us more connected or more isolated? 📱",
    "Veganism vs. carnivore diet: Which is healthier? 🥗🥩",
    "Do violent video games lead to real-world violence? 🎮",
    "Is Bitcoin the future of currency or just a bubble? 💰",
    "Are aliens real? Latest evidence and theories 👽",
    "Is nuclear energy the solution to climate change? ☢️",
    "Cancel culture: Necessary accountability or mob mentality? 🤐",
    "Is Universal Basic Income the solution to poverty? 💸",
    "Are we overdiagnosing ADHD and anxiety in children? 🧒",
    "Is monogamy natural or a social construct? 💑",
    "Should we colonize Mars or focus on saving Earth? 🌎🚀",
    "Is organic food worth the extra cost? 🥕",
    "Are zoos ethical or outdated? 🦁",
    "Is technology making us smarter or lazier? 🤓",
    "Should everyone learn to code, or is it overhyped? 💻",
        "Explain quantum computing 🖥️",
        "Best coffee brewing methods ☕",
        "Space tourism updates 🚀",
        "Sustainable fashion trends 👗",
        "Cryptocurrency market analysis 💰",
        "Most anticipated video games 🎮",
        "Healthy meal prep ideas 🥗",
        "Latest breakthroughs in renewable energy 🌞",
        "Tips for learning a new language 🗣️",
        "Virtual reality in education 🎓",
        "Global climate change initiatives 🌍",
        "Upcoming Marvel movies and shows 🦸",
        "Innovations in 3D printing technology 🖨️",
        "Mental health awareness campaigns 🧠",
        "Future of remote work trends 💼",
        "Advancements in medical robotics 🩺",
        "Popular podcasts recommendations 🎧",
        "Cybersecurity best practices 🔒",
        "Emerging social media platforms 📱",
        "DIY home improvement projects 🏠",
        "Latest discoveries in astronomy 🔭",
        "Eco-friendly travel destinations 🏝️",
        "Breakthrough in battery technology 🔋",
        "Mindfulness and meditation techniques 🧘",
        "Cutting-edge wearable tech gadgets ⌚",
        "Trends in plant-based diets 🥬",
        "Advances in gene editing technology 🧬",
        "Electric vehicle innovations 🚗",
        "Blockchain applications beyond crypto 🔗",
        "Developments in augmented reality 👓",
        "Innovative urban farming techniques 🌱",
        "Latest in artificial neural networks 🧠",
        "Breakthroughs in fusion energy research ⚛️",
        "Trends in minimalist lifestyle 🏡",
        "Advancements in prosthetic limbs 🦾",
        "Future of personalized medicine 💊",
        "Innovations in water purification 💧",
        "Developments in quantum cryptography 🔐",
        "Trends in sustainable architecture 🏗️",
        "Breakthroughs in longevity research 🧪",
        "Advancements in brain-computer interfaces 🧠💻",
        "Latest in drone technology 🛸",
        "Innovations in vertical farming 🌿",
        "Developments in lab-grown meat 🥩",
        "Trends in digital art and NFTs 🎨",
        "Best smartphones under $500 📱",
        "Easy dinner recipes for beginners 🍳",
        "How to remove wine stains from carpet 🍷",
        "Upcoming Marvel movies release dates 🦸",
        "Tips for better sleep 😴",
        "DIY home organization ideas 🏠",
        "Best online courses for learning Python 🐍",
        "How to start a vegetable garden 🥕",
        "Cryptocurrency explained simply 💰",
        "Healthy snack ideas for kids 🍎",
        "Latest fashion trends for summer 👗",
        "How to build a budget gaming PC 🖥️",
        "Tips for reducing plastic waste ♻️",
        "Best true crime podcasts 🎧",
        "How to make cold brew coffee at home ☕",
        "Beginner's guide to yoga 🧘",
        "Easy houseplants for beginners 🌿",
        "How to create a successful LinkedIn profile 💼",
        "Quick workouts for busy people 🏋️",
        "Tips for writing a resume 📄",
        "Best board games for family night 🎲",
        "How to start meditation 🧘‍♀️",
        "Easy makeup tutorials for beginners 💄",
        "Tips for better smartphone photography 📸",
        "How to make homemade pizza 🍕",
        "Best audiobooks for road trips 🚗",
        "How to tie a tie 👔",
        "Tips for decluttering your home 🧹",
        "How to change a car tire 🔧",
        "Best free apps for learning a new language 🗣️",
        "How to make kombucha at home 🍵",
        "Tips for growing herbs indoors 🌿",
        "How to create a YouTube channel 🎥",
        "Best documentaries on Netflix 🎬",
        "How to start journaling for mental health 📓",
        "Tips for improving posture while working from home 💺",
        "How to make homemade ice cream 🍦",
        "Best podcasts for self-improvement 🎧",
        "How to create a capsule wardrobe 👚",
        "Tips for reducing food waste 🥬",
        "How to start a book club 📚",
        "Best free online workout videos 💪",
        "How to make sourdough bread 🍞",
        "Tips for better time management ⏰",
        "How to start birdwatching 🐦",
        "Best apps for mindfulness and meditation 🧘‍♂️",
        "How to create a successful Etsy shop 🛍️",
        "Tips for better public speaking 🎤"
];