export const initialQuestions = [
"US election 2024 🇺🇸",
"Best movies of 2024 🎬",
"OpenAI o1 Mini vs Claude 3.5 Sonnet 🤖",
"iPhone 16📱",
"P. Diddy allegations 🎤",
"P diddy",
"UEFA Champions League 🏆",
"Joker 2 review 🎬",
"Kamala Harris vs Donald Trump 2024 🇺🇸",
"Oasis reunion 🎸",
"The Nobel Prize in Physics 2024 🏆",
"Why the Nobel Prize in Physics Was Awarded to AI 🧠",
    "How do I make lean 🍇",
    "How to pretend I know what I'm doing at my internship 💼",
    "How to look awake in 8 AM classes ☕",
    "Why does my student debt keep growing? 💰",
    "How to convince my parents I'm not wasting my life 👨‍👩‍👧",
    "Why am I always broke AF? 💸",
    "How to wake my dumbass up 🌞",
    "Why my cheap-ass coffee tastes like crap 🤮",
    "How to trick my brain into not being a lazy bum 🧠",
    "Why tf is adulting so freaking hard 😭",
    "How to make my crappy apartment look bougie AF 🏠",
    "Why my dumb cat won't stop being a jerk 😾",
    "How to look smart when I'm dumb as heck 🤓",
    "Why my broke self can't stop buying useless junk 💸",
    "How to convince my boss I'm not a total screw-up 👔",
    "Why my legs hurt like crazy after leg day 🦵",
    "How to stop being a hot mess for 5 dang minutes 🔥",
    "Why does my singing sound like a dying whale 🎤",
    "How to fake being a responsible adult 🥸",
    "Why is my Wi-Fi slower than a snail 🐌",
    "How to not look like an idiot on a first date 💑",
    "Why does my car make that weird-ass noise 🚗",
    "How to pretend I know what I'm doing at work 💼",
    "Why do I always look stoned in photos 📸",
    "How to cook something that doesn't taste like cardboard 🍳",
    "Why is my phone battery always freakin' dead ⚡",
    "How to make friends when I'm awkward AF 🤦",
    "Why does my attempt at art look like a toddler did it 🎨",
    "How to not kill my plants for once 🌱",
    "Why does my gym motivation last like 2 seconds 🏋️",
    "How to look like I slept when I'm dead tired 😴",
    "Why does my hair have a mind of its own 💇",
    "How to adult without having a breakdown 😅",
    "Why does my dog eat everything but actual dog food 🐶",
    "How to fake being a social butterfly 🦋",
    "Why is my love life such a dumpster fire 💔",
        "AGI when? 🤖", "Mars colony 🔴", "Flying cars yet? 🚗", "Immortality soon? ⏳", "Teleportation real? 🌀", "Cure for cancer 🧬", "Time travel possible? ⏰", "Aliens exist? 👽", "Singularity near? 💥", "Matrix reality? 🕶️", "Mind uploading? 🧠", "Fusion energy when? ⚡", "End of work? 💼", "Universal income 💰", "Space elevator? 🚀", "Nanobots medical 💉", "Quantum internet 🌐", "Hologram phones? 📞", "Universal translator? 🗣️", "Weather control? 🌦️", "Underwater cities? 🌊", "Brain-computer link? 🔌",
        "Drone regulations 🛸", "Big tech antitrust 🏛️", "Social media privacy 🔐", "Foldable phones 📲", "AI art generators 🎨", "Blockchain use cases 🔗", "Tech IPOs 📈", "Chip shortage 🖥️", 
        "Biometric security 👁️", "Edge computing 🌐", "3D printing advances 🖨️", "Tech layoffs 💼", "Green tech innovations 🌿", "Metaverse developments 🌐", "Robotic automation 🦾", "App store policies 📱", "Tech earnings reports 💹", "Data breach news 🚨",
        "Messi news", "FC Barcelona Transfer News & Rumours 🔴🔵", "Ronaldo goal count ⚽", "Lebron retirement? 🏀", "Serena comeback 🎾", "Brady NFL return 🏈", "Djokovic visa drama 🛂", "McGregor next fight 🥊", "Simone Biles routine 🤸", "Neymar transfer news 💰", "Osaka mental health 🧠", "Tiger Woods PGA 🏌️", "Curry 3-point record 🏀", "Mbappé Real Madrid contract 📝", "Nadal clay record 🏆", "Hamilton F1 future 🏎️", "Federer farewell tour 👋", "Rapinoe equal pay ⚖️", "Salah golden boot 👟", "Phelps comeback swim 🏊", "Biles Olympic return 🥇",
        "Taylor Swift boyfriend 💑", "BTS military service 🪖", "Kanye West rants 🎤", "Rihanna baby pics 👶", "Tom Cruise stunts 🎬", "Beyoncé tour tickets 🎫", "Harry Styles dating 💘", "Adele Vegas residency 🎰", "Kardashian drama 💄", "Billie Eilish hair color 💇", "Timothée Chalamet dating 🌟", "Chris Rock slap joke 👋", "Lady Gaga Joker 2 🃏", "Ariana Grande wedding 👰", "Johnny Depp comeback 🏴‍☠️", "Selena Gomez lupus 🩺", "Dua Lipa dance moves 💃", "Marvel Phase 5 leak 🦸",
        "ChatGPT stock 📈", "iPhone 16 camera 📷", "Tesla Bot price 🤖", "Tech layoffs 💼", "TikTok ban update 🚫", "Starlink speeds 🛰️", "RTX 4090 restock 🖥️", "Apple VR headset leak 🥽", "Google AI sentient? 🧠", "Cyberpunk 2077 patch 🎮", "Twitter edit button 🐦", "Facebook metaverse 🌐", "AWS outage cause ☁️", "Chrome zero-day fix 🔒", "SpaceX Mars mission 🚀", "Pixel Fold release 📱", "Steam Deck mods 🎮", "The Biggest Stock Market Crashes in Modern History 📉", "Windows 12 features 💻", "Reddit IPO when? 💰",
        "ChatGPT 🤖",
        "Scranton Strangler",
        "Michael Jackson 🎵",
        "The Beatles 🎵",
        "Residual neural networks 🧠",
        "Taylor Swift 🎵",
        "Kanye West 🎵",
        "duckduckgo vs google 🦆",
        "Nike vs Adidas 👟",
        "Elon Musk 🚀",
        "Tesla 🚗",
        "SpaceX 🚀",
        "Starlink 🛰️",
        "Neuralink 🧠",
        "OpenAI 🤖",
        "DeepMind 🧠",
        "Latest AI news 📰",
        "Funny memes about work 🤣",
        "Kindle link to The Hobbit 📚",
        "Nvidia stock price analysis 📈",
        "Cute dog videos 🐶",
        "Top Netflix shows this month 📺",
        "Funny cat fails compilation 😹",
        "Best gaming laptops 2024 🎮",
        "Popular indie games 2024 🎮",
        "Trending TikTok dances tutorial 💃",
        "How to register to vote in the us 🗳️",
        "Messi vs Ronaldo ⚽",
        "Kendrick Lamar vs Drake: Who won the beef? 🎤",
        "How many people did Pieter Levels mute on Twitter? 🤐",
        "Charli XCX new album review 🎵",
        "Is Kanye West crazy or a genius…or both? Or neither? 🤔",
        "How would you rank the main characters of 'The Office' in terms of their productivity at Dunder Mifflin? 📊",
        "Why do some people believe the Earth is flat? 🌍",
            "Tesla Model 3 vs Ford Mustang Mach-E 🚗",
            "What are some potential applications of AI in physics that we haven't seen yet? 🤔",
            "Is autonomous driving ever going to be a thing? 🚗",
            "Will AI eventually replace human artists and musicians? 🎨🎵",
            "Are we living in a simulation? Matrix theory explained 🕴️",
            "Is social media making us more connected or more isolated? 📱",
            "Veganism vs. carnivore diet: Which is healthier? 🥗🥩",
            "Do violent video games lead to real-world violence? 🎮",
            "Is Bitcoin the future of currency or just a bubble? 💰",
            "Are aliens real? Latest evidence and theories 👽",
            "Is nuclear energy the solution to climate change? ☢️",
            "Cancel culture: Necessary accountability or mob mentality? 🤐",
            "Is Universal Basic Income the solution to poverty? 💸",
            "Are we overdiagnosing ADHD and anxiety in children? 🧒",
            "Is monogamy natural or a social construct? 💑",
            "Why does SpaceX want to colonize Mars? 🧑‍🚀",
            "Is organic food worth the extra cost? 🥕",
            "Are zoos ethical or outdated? 🦁",
            "Is technology making us smarter or lazier? 🤓",
            "Should everyone learn to code, or is it overhyped? 💻",
            "Is free will an illusion? Determinism vs. free will debate 🤔",
            "The Fermi Paradox: Where is everybody in the universe? 👽",
            "Is the multiverse theory science fiction or a real possibility? 🌌",
            "Is cryptocurrency the future of money or a passing fad? 💰",
            "The Mandela Effect: Evidence of parallel universes? 🌀",
            "The Chinese room argument: Can AI truly understand? 🈯",
            "Is time travel possible, and if so, where are all the time travelers? ⏳",
            "Media bias: How to spot it and why it matters 📰",
            "Is legacy media dying, and what will replace it? 📺",
            "The rise of deepfake technology: Threats and opportunities 🎭",
            "The ethics of gene editing: Designer babies and beyond 🧬",
            "The future of work: Automation, AI, and the gig economy 💼",
            "The dark side of social media: Mental health and misinformation 📱",
            "The future of education: Online learning, AI tutors, and more 🎓",
            "The psychology of conspiracy theories: Why do people believe them? 🤯",
                "Is global warming real? or is it a hoax? 🌍",
                "Is the earth flat or round? 🌎",
                "Is the moon landing real? 🌕",
                "Explain quantum computing 🖥️",
                "Best coffee brewing methods ☕",
                "Space tourism updates 🚀",
                "Cryptocurrency market analysis 💰",
                "Most anticipated video games 🎮",
                "Healthy meal prep ideas 🥗",
                "Latest breakthroughs in renewable energy 🌞",
                "Tips for learning a new language 🗣️",
                "Virtual reality in education 🎓",
                "Global climate change initiatives 🌍",
                "Upcoming Marvel movies and shows 🦸",
                "Innovations in 3D printing technology 🖨️",
                "Mental health awareness campaigns 🧠",
                "Future of remote work trends 💼",
                "Advancements in medical robotics 🩺",
                "Popular podcasts recommendations 🎧",
                "Cybersecurity best practices 🔒",
                "Emerging social media platforms 📱",
                "DIY home improvement projects 🏠",
                "Latest discoveries in astronomy 🔭",
                "Eco-friendly travel destinations 🏝️",
                "Breakthrough in battery technology 🔋",
                "Mindfulness and meditation techniques 🧘",
                "Cutting-edge wearable tech gadgets ⌚",
                "Trends in plant-based diets 🥬",
                "Advances in gene editing technology 🧬",
                "Electric vehicle innovations 🚗",
                "Blockchain applications beyond crypto 🔗",
                "Developments in augmented reality 👓",
                "Innovative urban farming techniques 🌱",
                "Latest in artificial neural networks 🧠",
                "Breakthroughs in fusion energy research ⚛️",
                "Trends in minimalist lifestyle 🏡",
                "Advancements in prosthetic limbs 🦾",
                "Future of personalized medicine 💊",
                "Innovations in water purification 💧",
                "Developments in quantum cryptography 🔐",
                "Trends in sustainable architecture 🏗️",
                "Breakthroughs in longevity research 🧪",
                "Advancements in brain-computer interfaces 💻",
                "Latest in drone technology 🛸",
                "Innovations in vertical farming 🌿",
                "Developments in lab-grown meat 🥩",
                "Trends in digital art and NFTs 🎨",
                "NFT art market analysis 🎨",
                "Best smartphones under $500 📱",
                "Easy dinner recipes for beginners 🍳",
                "How to remove wine stains from carpet 🍷",
                "Upcoming Marvel movies release dates 🦸",
                "Tips for better sleep 😴",
                "DIY home organization ideas 🏠",
                "Best online courses for learning Python 🐍",
                "How to start a vegetable garden 🥕",
                "Cryptocurrency explained simply 💰",
                "Healthy snack ideas for kids 🍎",
                "Latest fashion trends for summer 👗",
                "Tips for reducing plastic waste ♻️",
                "Best true crime podcasts 🎧",
                "Beginner's guide to yoga 🧘",
                "Easy houseplants for beginners 🌿",
                "Quick workouts for busy people 🏋️",
                "Tips for writing a resume 📄",
                "Best board games for family night 🎲",
                "Easy makeup tutorials for beginners 💄",
                "How to make homemade pizza 🍕",
                "Best audiobooks for road trips 🚗",
                "How to tie a tie 👔",
                "Best free apps for learning a new language 🗣️",
                "How to make kombucha at home 🍵",
                "How to create a YouTube channel 🎥",
                "Best documentaries on Netflix 🎬",
                "How to start journaling for mental health 📓",
                "Best podcasts for self-improvement 🎧",
                "How to create a capsule wardrobe 👚",
                "Best free online workout videos 💪",
                "How to start birdwatching 🐦",
                "Best apps for mindfulness and meditation 🧘‍♂️",
                "How to create a successful Etsy shop 🛍️",
                "Web3 and decentralized internet explained 🌐",
                "Space tourism companies comparison 🚀",
                "Metaverse real estate investment guide 🏙️",
                "5G vs 6G technology comparison 📡",
        ];